### ISSUE TITLE
Build fails using Java 9 or 10

### ISSUE THREAD

**Issue by McPringle** [JavaMoney/jsr354-api#70]
**Steps to reproduce**
- Install and activate Java 9 or Java 10 (in my case: official stable OpenJDK builds)
- Clone this repository: `git clone git@github.com:JavaMoney/jsr354-api.git`
- Enter project directory: `cd jsr354-api`
- Build the project: `mvn clean package`

**Actual result**
- Build failure

**Expected result**
- Build successful

**Versions**
- Java 9: openjdk version "9.0.4"
- Java 10: openjdk version "10" 2018-03-20

**Build output Java 9**
```
[INFO] Scanning for projects...
[WARNING] The project javax.money:money-api:bundle:1.0.2-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] 
[INFO] -----------------------< javax.money:money-api >------------------------
[INFO] Building JSR 354 (Money and Currency API) 1.0.2-SNAPSHOT
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ money-api ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ money-api ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.2.201409121644:prepare-agent (prepare-agent) @ money-api ---
[INFO] argLine set to -javaagent:/Users/mcpringle/.m2/repository/org/jacoco/org.jacoco.agent/0.7.2.201409121644/org.jacoco.agent-0.7.2.201409121644-runtime.jar=destfile=/Users/mcpringle/tmp/jsr354-api/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ money-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/mcpringle/tmp/jsr354-api/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ money-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 67 source files to /Users/mcpringle/tmp/jsr354-api/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ money-api ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 8 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ money-api ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 54 source files to /Users/mcpringle/tmp/jsr354-api/target/test-classes
[WARNING] /Users/mcpringle/tmp/jsr354-api/src/test/java/javax/money/AbstractDynamicServiceProviderTest.java: /Users/mcpringle/tmp/jsr354-api/src/test/java/javax/money/AbstractDynamicServiceProviderTest.java uses unchecked or unsafe operations.
[WARNING] /Users/mcpringle/tmp/jsr354-api/src/test/java/javax/money/AbstractDynamicServiceProviderTest.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- maven-surefire-plugin:2.15:test (default-test) @ money-api ---
[INFO] Surefire report directory: /Users/mcpringle/tmp/jsr354-api/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(InstrumentationImpl.java:500)
	at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(InstrumentationImpl.java:512)
Caused by: java.lang.RuntimeException: Class java/util/UUID could not be instrumented.
	at org.jacoco.agent.rt.internal_e6e56f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:139)
	at org.jacoco.agent.rt.internal_e6e56f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:100)
	at org.jacoco.agent.rt.internal_e6e56f0.PreMain.createRuntime(PreMain.java:55)
	at org.jacoco.agent.rt.internal_e6e56f0.PreMain.premain(PreMain.java:47)
	... 6 more
Caused by: java.lang.NoSuchFieldException: $jacocoAccess
	at java.base/java.lang.Class.getField(Class.java:1956)
	at org.jacoco.agent.rt.internal_e6e56f0.core.runtime.ModifiedSystemClassRuntime.createFor(ModifiedSystemClassRuntime.java:137)
	... 9 more
FATAL ERROR in native method: processing of -javaagent failed
/bin/sh: line 1: 16776 Abort trap: 6           /Users/mcpringle/Applications/OpenJDK/9-openjdk/bin/java -javaagent:/Users/mcpringle/.m2/repository/org/jacoco/org.jacoco.agent/0.7.2.201409121644/org.jacoco.agent-0.7.2.201409121644-runtime.jar=destfile=/Users/mcpringle/tmp/jsr354-api/target/jacoco.exec -jar /Users/mcpringle/tmp/jsr354-api/target/surefire/surefirebooter6419662123901029719.jar /Users/mcpringle/tmp/jsr354-api/target/surefire/surefire12098304876579567375tmp /Users/mcpringle/tmp/jsr354-api/target/surefire/surefire_010893056284371472417tmp

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 9.027 s
[INFO] Finished at: 2018-03-30T06:43:38+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test (default-test) on project money-api: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.15:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ?
[ERROR] Command was/bin/sh -c cd /Users/mcpringle/tmp/jsr354-api && /Users/mcpringle/Applications/OpenJDK/9-openjdk/bin/java -javaagent:/Users/mcpringle/.m2/repository/org/jacoco/org.jacoco.agent/0.7.2.201409121644/org.jacoco.agent-0.7.2.201409121644-runtime.jar=destfile=/Users/mcpringle/tmp/jsr354-api/target/jacoco.exec -jar /Users/mcpringle/tmp/jsr354-api/target/surefire/surefirebooter6419662123901029719.jar /Users/mcpringle/tmp/jsr354-api/target/surefire/surefire12098304876579567375tmp /Users/mcpringle/tmp/jsr354-api/target/surefire/surefire_010893056284371472417tmp
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

**Build output Java 10**
```
[INFO] Scanning for projects...
[WARNING] The project javax.money:money-api:bundle:1.0.2-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] 
[INFO] -----------------------< javax.money:money-api >------------------------
[INFO] Building JSR 354 (Money and Currency API) 1.0.2-SNAPSHOT
[INFO] -------------------------------[ bundle ]-------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ money-api ---
[INFO] Deleting /Users/mcpringle/tmp/jsr354-api/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.3.1:enforce (enforce-versions) @ money-api ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.086 s
[INFO] Finished at: 2018-03-30T06:45:32+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce-versions) on project money-api: Execution enforce-versions of goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce: java.lang.ExceptionInInitializerError: null
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>org.apache.maven.plugins:maven-enforcer-plugin:1.3.1
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/Users/mcpringle/.m2/repository/org/apache/maven/plugins/maven-enforcer-plugin/1.3.1/maven-enforcer-plugin-1.3.1.jar
[ERROR] urls[1] = file:/Users/mcpringle/.m2/repository/org/apache/maven/reporting/maven-reporting-api/2.0.9/maven-reporting-api-2.0.9.jar
[ERROR] urls[2] = file:/Users/mcpringle/.m2/repository/org/apache/maven/doxia/doxia-sink-api/1.0-alpha-10/doxia-sink-api-1.0-alpha-10.jar
[ERROR] urls[3] = file:/Users/mcpringle/.m2/repository/commons-cli/commons-cli/1.0/commons-cli-1.0.jar
[ERROR] urls[4] = file:/Users/mcpringle/.m2/repository/org/codehaus/plexus/plexus-interactivity-api/1.0-alpha-4/plexus-interactivity-api-1.0-alpha-4.jar
[ERROR] urls[5] = file:/Users/mcpringle/.m2/repository/org/codehaus/plexus/plexus-utils/1.5.8/plexus-utils-1.5.8.jar
[ERROR] urls[6] = file:/Users/mcpringle/.m2/repository/commons-lang/commons-lang/2.3/commons-lang-2.3.jar
[ERROR] urls[7] = file:/Users/mcpringle/.m2/repository/org/apache/maven/enforcer/enforcer-api/1.3.1/enforcer-api-1.3.1.jar
[ERROR] urls[8] = file:/Users/mcpringle/.m2/repository/org/apache/maven/enforcer/enforcer-rules/1.3.1/enforcer-rules-1.3.1.jar
[ERROR] urls[9] = file:/Users/mcpringle/.m2/repository/org/apache/maven/shared/maven-common-artifact-filters/1.4/maven-common-artifact-filters-1.4.jar
[ERROR] urls[10] = file:/Users/mcpringle/.m2/repository/org/beanshell/bsh/2.0b4/bsh-2.0b4.jar
[ERROR] urls[11] = file:/Users/mcpringle/.m2/repository/org/apache/maven/shared/maven-dependency-tree/2.1/maven-dependency-tree-2.1.jar
[ERROR] urls[12] = file:/Users/mcpringle/.m2/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[13] = file:/Users/mcpringle/.m2/repository/org/eclipse/aether/aether-util/0.9.0.M2/aether-util-0.9.0.M2.jar
[ERROR] urls[14] = file:/Users/mcpringle/.m2/repository/org/codehaus/plexus/plexus-i18n/1.0-beta-6/plexus-i18n-1.0-beta-6.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[project>javax.money:money-api:1.0.2-SNAPSHOT, parent: ClassRealm[maven.api, parent: null]]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : begin 0, end 3, length 2
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException
```

**Comment by atsticks** [comment]
Fixed with Java 9 module support, used Oracle JDK version "9.0.4".

**Comment by McPringle** [comment]
I can confirm the build finishes successfully using Java 9.0.4. Bite with Java 10.0.0 the build still fails with the error message from above. I created a new issue to focus on the Java 10 problem: #71

**Comment by keilw** [comment]
Then as mentioned there it looks a lot like certain Maven plugins have not been tested or adopted to Java 10 yet. It does not seem like a problem with the API itself.
